---
env:
  uat: mobilefirst
  dev: mobiledev
  qa: qa
  staging: staging

api:
  login: /services/api/mobile/service/login
  studycontext: /services/api/mobile/service/studycontext
  coursestructure: /services/api/mobile/service/coursestructure
  activitycontent: /services/api/mobile/service/activitycontent

dla:
  platform: Android
  culturecode: en
  countryCode: us
  partnerCode: Corp
  siteVersion: development
  appVersion: 2.0.2
  productId: 2

ec:
  platform: Android
  culturecode: en
  countryCode: cn
  partnerCode: Cool
  siteVersion: development
  appVersion: 0.7.0
  productId: 4